### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by phelixose** [hangsz/pandas-tutorial#1]
感谢楼主的辛勤劳动。我使用这个教程有个问题，我的jupyter是5.0.0.，导入你的ipynb出错，显示“Unreadable Notebook: C:\Users\Administrator\Desktop\0. 配置环境.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...",)”。这个怎么解决呢？

**Comment by hangsz** [comment]
我的jupyter 版本是4.3.0，或许是这个原因。
