### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by 521xueweihan** [hangsz/pandas-tutorial#4]
最近在使用 pandas，正如你所说的 “pandas 的文档为了保证完整性导致有价值的东西隐匿”。所以，促使我找到了你的这个项目。:trollface:

而你写的教程逻辑连贯、清晰，每章都是常用的知识点。不管是用作 cheat sheet 还是入门、进阶教程都是非常适合的。我会收录到我的 HelloGitHub 项目，希望更多人看到你的项目。

最后是我的一些建议：

**建议：**
- 在 `README.md` 中加入目录，折叠语法：`<details></details>`
- 关于性能对比和解释，比如不推荐 `for` 循环 row 操作，多采用 colum 的

**Comment by hangsz** [comment]
好的，我会修改的。
目前教程还没写完，而且还有需要完善的地方，不过实在没什么时间。
多谢推广了，希望你的项目能帮助更多的人。

**Comment by 521xueweihan** [comment]
@hangsz 嗯，好的，我会继续把 HelloGitHub 做下去。

你也加油，你的项目真的非常有价值！

**Comment by angerlover** [comment]
大神不更新了吗

**Comment by hangsz** [comment]
更不更新看大家需求吧，主要是觉得前边基础学会后，后面自然也就会了，入门了就容易了。
另一方面是工作后太忙了，闲下来也想搞点别的事，这块就没花时间了。
如果大家觉得确实需要更新，我会抽时间更新。

Pepe <notifications@github.com> 于2019年6月10日周一 下午2:01写道：
