### ISSUE TITLE
一点文字的错误

### ISSUE THREAD

**Issue by Sum41forever** [hangsz/pandas-tutorial#5]
![image](https://user-images.githubusercontent.com/18468976/36523169-51c601d2-17db-11e8-8e45-4827212dc632.png)

# 2. Series和DataFrame对象的查、改、增、删.ipynb

1.1.3 .iloc[]，基于位置
无视索引，只安装位置定位。

应该是只按照位置定位

**Comment by hangsz** [comment]
好的，thx。
